version: '3'
services:

  prometheus:
     image: prom/prometheus:v2.44.0
     container_name: prometheus
     volumes:
       - ./prometheus:/etc/prometheus
     ports:
       - 9090:9090
     command:
     - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
