global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'jenkins_job'
    metrics_path: /prometheus/
    static_configs:
    - targets: ['host.docker.internal:8080']
